services:
  db:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_USER: jaimayal
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5232:5432"
    networks:
      - postgres
    restart: unless-stopped
  customers-api:
    container_name: customers-api
    image: jaimayal/customers-api
    ports:
      - "8081:8081"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db
    command:
      - "--spring.datasource.url=jdbc:postgresql://db:5432/customer"
  customers-frontend:
    container_name: customers-frontend
    image: jaimayal/customers-frontend
    ports:
      - "3000:5173"
    restart: unless-stopped
    build:
        context: frontend
        args:
            BASE_URL: http://localhost:8081
    depends_on:
      - customers-api

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: