services:
  db:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_USER: jaimayal
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5232:5432"
    networks:
      - postgres
    restart: unless-stopped
  customers-api:
    container_name: customers-api
    image: jaimayal/spring-customers-api
    ports:
      - "8081:8081"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db
    command:
      - "--spring.datasource.url=jdbc:postgresql://db:5432/customer"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: