# Server Config
server:
  port: 8081

# Database Config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5232/customer
    username: jaimayal
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    showSql: true
    hibernate:
      ddl-auto: validate
      
jwt:
  issuer: "https://jaimayal.github.io"
  expiration-seconds: 3600
  secret: "847a0778-0a83-43b1-ba2f-55c83126229f"

cors:
  allowed-origins: "http://localhost:5173, http://localhost:3000"
  allowed-methods: "GET, POST, PUT, DELETE, HEAD, OPTIONS"
  allowed-headers: "Authorization, Host, User-Agent, Content-Type, Accept, Accept-Encoding, Origin, X-Requested-With"
  exposed-headers: "Authorization, Host, User-Agent, Content-Type, Accept, Accept-Encoding, Origin, X-Requested-With"

logging:
  level:
    root: INFO