# Server Config
server:
  port: 8081

# Database Config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5232/customer
    username: jaimayal
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    showSql: true
    hibernate:
      ddl-auto: validate
      
jwt:
  issuer: "https://jaimayal.github.io"
  expiration-seconds: 3600
  secret: "847a0778-0a83-43b1-ba2f-55c83126229f"
  
logging:
  level:
    root: INFO