name: CD - Frontend
on:
  workflow_dispatch:
    push:
      branches:
        - "main"
      paths:
        - frontend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Generate Build Number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Docker Build
        run: docker build . --file Dockerfile --tag jaimayal/customers-frontend:${{steps.build-number.outputs.BUILD_NUMBER}}
      - name: Docker push
        run: docker push jaimayal/customers-frontend:${{steps.build-number.outputs.BUILD_NUMBER}}
      - name: Update Dockerrun.aws.json image tag with Build Number
          run: |
            echo "Dockerrun.aws.json before updating Docker Image Tag"
            cat ../Dockerrun.aws.json
            sed -i -E 's_(jaimayal/customers-frontend:)([^"]*)_\1'${{steps.build-number.outputs.BUILD_NUMBER}}'_' ../Dockerrun.aws.json
            echo "Dockerrun.aws.json after updating Docker Image Tag"
            cat ../Dockerrun.aws.json
      - name: Deploying new Dockerrun.aws.json to AWS Elastic Beanstalk
          run: echo "TODO"
      - name: Commit and Push updated Dockerrun.aws.json
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add ../Dockerrun.aws.json
            git commit -m "Updated Dockerrun.aws.json with new Build Tag ${{steps.build-number.outputs.BUILD_NUMBER}}"
            git push